project:
  type: website

website:
  title: "Working with data at HIP"
  navbar:
    left:
      - href: index.md
        text: Home
      - getting-set-up.qmd
      - using-github.qmd
      - code-guidelines.qmd
      - resources.qmd
    tools:
      - icon: github
        menu:
          - text: Website repository
            href:  https://github.com/housinginitiative/working-with-data
          - text: Make a suggestion
            href:  https://github.com/housinginitiative/working-with-data/issues/new
  favicon: images/HIP_favicon.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto



