project:
  type: website

website:
  title: "Working with data at HIP"
  navbar:
    left:
      - href: index.md
        text: Home
      - getting-set-up.qmd
      - using-github.qmd
      - code-guidelines.qmd
      - resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto



